[theme]
primaryColor="#99181c"
backgroundColor="#ececec"
secondaryBackgroundColor="#E8E3D9"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
